# -*- coding: utf-8 -*-
"""PlatinumRx Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IppI62f7rhpz0k4yqrQM5lOvuPc59dt_

1
"""

minutes = int(input("Enter minutes: "))

hours = minutes // 60
remaining_minutes = minutes % 60

if hours == 1:
  print(str(hours) + " hr " + str(remaining_minutes) + " minutes")
else:
  print(str(hours) + " hrs " + str(remaining_minutes) + " minutes")

"""2"""

text = input("Enter string: ")
result = ""

for ch in text:
  if ch not in result:
    result = result + ch

print("Output:", result)